FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libgl1 \
    ffmpeg \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --upgrade pip

COPY requirements-base.txt .
RUN pip install --no-cache-dir -r requirements-base.txt

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1